version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: myUserAdmin
      MONGO_INITDB_ROOT_PASSWORD: abc123

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo

volumes:
  mongo-data:
